<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use Illuminate\Support\Str;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Обов'язкові сторінки
        $staticPages = [
            [
                'uk' => 'Політика конфіденційності',
                'en' => 'Privacy Policy',
                'pl' => 'Polityka prywatności',
                'ru' => 'Политика конфиденциальности',
            ],
            [
                'uk' => 'Оплата та доставка',
                'en' => 'Payment and Delivery',
                'pl' => 'Płatność i dostawa',
                'ru' => 'Оплата и доставка',
            ],
            [
                'uk' => 'Повернення та обмін',
                'en' => 'Returns and Exchanges',
                'pl' => 'Zwroty и wymiana',
                'ru' => 'Возврат и обмен',
            ],
            [
                'uk' => 'Контакти',
                'en' => 'Contacts',
                'pl' => 'Kontakty',
                'ru' => 'Контакты',
            ],
            [
                'uk' => 'Про нас',
                'en' => 'About Us',
                'pl' => 'O nas',
                'ru' => 'О нас',
            ],
        ];

        foreach ($staticPages as $index => $titles) {
            $page = Page::create([
                'public' => true,
                'order' => $index + 1,
            ]);

            $translations = [];
            foreach ($titles as $locale => $title) {
                $translations[] = [
                    'locale'           => $locale,
                    'title'            => $title,
                    'slug'             => Str::slug($title),
                    'description'      => "Description for $title",
                    'content'          => "<p>Content for $title page. This is a static page generated by seeder.</p>",
                    'meta_title'       => $title,
                    'meta_description' => "Meta description for $title",
                    'meta_keywords'    => "keywords, $title",
                ];
            }

            $page->translations()->createMany($translations);
        }

        // 2. Додатково створюємо рандомні сторінки через фабрику, якщо потрібно
        Page::factory()->count(1)->create();
    }
}
