import "ckeditor5/ckeditor5.css";
import {
    ClassicEditor,
    FindAndReplace,
    Undo,
    Heading,
    RemoveFormat,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Code,
    Subscript,
    Superscript,
    Link,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    List,
    ListProperties,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageInsert,
    LinkImage,
    SimpleUploadAdapter,
    BlockQuote,
    Alignment,
    Indent,
    IndentBlock,
    SourceEditing,
    Fullscreen,
    Font,
    MediaEmbed,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Emoji,
    Mention,
} from "ckeditor5";

import Footnote from "./Footnote/footnote";
import "./Footnote/footnote.css";

import MathType from "@wiris/mathtype-ckeditor5/dist/index.js";

export default class CKEditor extends ClassicEditor {}

CKEditor.builtinPlugins = [
    FindAndReplace,
    Undo,
    Heading,
    RemoveFormat,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Code,
    Subscript,
    Superscript,
    Link,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    Footnote,
    List,
    ListProperties,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageInsert,
    LinkImage,
    SimpleUploadAdapter,
    BlockQuote,
    Alignment,
    Indent,
    IndentBlock,
    SourceEditing,
    Fullscreen,
    Font,
    MediaEmbed,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Emoji,
    Mention,
    //MathType,
];

CKEditor.defaultConfig = {
    licenseKey: "GPL",
    language: "en",
    plugins: CKEditor.builtinPlugins,
    heading: {
        options: [
            {
                model: "paragraph",
                title: "Paragraph",
                class: "ck-heading_paragraph",
            },
            {
                model: "heading1",
                view: "h1",
                title: "Heading 1",
                class: "ck-heading_heading1",
            },
            {
                model: "heading2",
                view: "h2",
                title: "Heading 2",
                class: "ck-heading_heading2",
            },
            {
                model: "heading3",
                view: "h3",
                title: "Heading 3",
                class: "ck-heading_heading3",
            },
        ],
    },
    table: {
        //defaultHeadings: { rows: 1, columns: 1 },
        contentToolbar: [
            "tableColumn",
            "tableRow",
            "mergeTableCells",
            "tableProperties", // ← Додано до контекстної панелі таблиці
            "tableCellProperties", // ← Додано до контекстної панелі таблиці
        ],
    },
    list: {
        properties: {
            styles: true,
            startIndex: true,
            reversed: true,
        },
    },
    image: {
        insert: {
            integrations: ["upload", "url"],
        },
        toolbar: [
            "imageStyle:block",
            "imageStyle:side",
            "|",
            "toggleImageCaption",
            "imageTextAlternative",
            "|",
            "linkImage",
        ],
    },
    simpleUpload: {
        uploadUrl: route("api.upload.image"),
        withCredentials: true,
    },
    emoji: {
        dropdownLimit: 5,
        skinTone: "medium",
    },

    fontSize: {
        options: [
            10,
            12,
            14,
            16,
            { title: "Default", model: "18px" }, // Встановлюємо 18px як опцію "Default"
            20,
            22,
            24,
            26,
            36,
            48,
        ],
        supportAllValues: true,
    },

    toolbar: [
        "findAndReplace",

        "|",
        "undo",
        "redo",
        "|",
        "removeFormat",
        "heading",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "code",
        "|",
        //"MathType",
        //"ChemType",
        "subscript",
        "superscript",
        "|",
        "fontSize",
        "fontFamily",
        "fontColor",
        "fontBackgroundColor",
        "|",
        "alignment",
        "outdent",
        "indent",
        "|",
        "insertFootnote",
        "link",
        "insertTable",
        "insertImage",
        //"mediaEmbed",

        "|",
        "emoji",
        "specialCharacters",
        "blockQuote",

        "bulletedList",
        "numberedList",

        "|",
        "sourceEditing",
        "|",
        "fullscreen",
    ],
};
