import "ckeditor5/ckeditor5.css";
import {
    Alignment,
    Autoformat,
    BlockQuote,
    Bold,
    Code,
    ClassicEditor,
    Essentials,
    FindAndReplace,
    Font,
    FontFamily,
    Heading,
    HeadingButtonsUI,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    Indent,
    IndentBlock,
    Italic,
    LinkImage,
    MediaEmbed,
    Paragraph,
    ParagraphButtonUI,
    SimpleUploadAdapter,
    Strikethrough,
    Subscript,
    Superscript,
    SpecialCharacters,
    SpecialCharactersEssentials,
    TextTransformation,
    Underline,
    AutoLink,
    Link,
    Table,
    TableCellProperties,
    TableProperties,
    TableToolbar,
} from "ckeditor5";

export default class CKEditor extends ClassicEditor {}

CKEditor.builtinPlugins = [
    Alignment,
    Autoformat,
    BlockQuote,
    Bold,
    Code,
    Essentials,
    FindAndReplace,
    Font,
    FontFamily,
    Heading,
    HeadingButtonsUI,
    Image,
    ImageCaption,
    ImageInsert,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    Indent,
    IndentBlock,
    Italic,
    LinkImage,
    MediaEmbed,
    Paragraph,
    ParagraphButtonUI,
    SimpleUploadAdapter,
    Strikethrough,
    Subscript,
    Superscript,
    SpecialCharacters,
    SpecialCharactersEssentials,
    TextTransformation,
    Underline,
    AutoLink,
    Link,
    Table,
    TableCellProperties,
    TableProperties,
    TableToolbar,
];

CKEditor.defaultConfig = {
    licenseKey: "GPL",
    plugins: [
        Alignment,
        Autoformat,
        BlockQuote,
        Bold,
        Code,
        Essentials,
        FindAndReplace,
        Font,
        FontFamily,
        Heading,
        HeadingButtonsUI,
        Image,
        ImageCaption,
        ImageInsert,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        Indent,
        IndentBlock,
        Italic,
        LinkImage,
        MediaEmbed,
        Paragraph,
        ParagraphButtonUI,
        SimpleUploadAdapter,
        Strikethrough,
        Subscript,
        Superscript,
        SpecialCharacters,
        SpecialCharactersEssentials,
        TextTransformation,
        Underline,
        AutoLink,
        Link,
        Table,
        TableCellProperties,
        TableProperties,
        TableToolbar,
    ],
    fontSize: {
        options: [9, 11, 13, "default", 17, 19, 21],
    },
    image: {
        insert: {
            integrations: ["upload", "url"],
        },
        toolbar: [
            "imageStyle:block",
            "imageStyle:side",
            "|",
            "toggleImageCaption",
            "imageTextAlternative",
            "|",
            "linkImage",
        ],
    },
    simpleUpload: {
        uploadUrl: route("api.upload.image"),
        withCredentials: true,
    },
    toolbar: [
        "undo",
        "redo",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "subscript",
        "superscript",
        "code",
        "|",
        "insertTable",
        "|",
        "fontSize",
        "fontFamily",
        "fontColor",
        "fontBackgroundColor",
        "|",
        "alignment",
        "blockQuote",
        "outdent",
        "indent",
        "|",
        "findAndReplace",
        "specialCharacters",
        "insertImage",
        "mediaEmbed",
        "|",
        "link",
        {
            label: "Others",
            tooltip: "Basic formatting features",
            items: ["bold", "italic"],
        },
    ],
    table: {
        contentToolbar: [
            "tableColumn",
            "tableRow",
            "mergeTableCells",
            "tableProperties",
            "tableCellProperties",
        ],

        tableProperties: {
            //
        },

        tableCellProperties: {
            //
        },
    },
};
