// resources/js/Config/ckeditor.js
import {
    FindAndReplace,
    Undo,
    Heading,
    RemoveFormat,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    Code,
    Subscript,
    Superscript,
    Link,
    Table,
    TableToolbar,
    TableProperties,
    TableCellProperties,
    List,
    ListProperties,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageInsert,
    LinkImage,
    SimpleUploadAdapter,
    BlockQuote,
    Alignment,
    Indent,
    IndentBlock,
    SourceEditing,
    Fullscreen,
    Font,
    MediaEmbed,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Emoji,
    Mention,
} from "ckeditor5";

// Твої кастомні плагіни (коригуй шляхи відносно папки Config, якщо потрібно)
import Footnote from "../plugins/Footnote/footnote.js";

export const ckeditorConfig = {
    licenseKey: "GPL",
    language: "en",

    // Реєструємо всі плагіни, включаючи активований MathType
    plugins: [
        FindAndReplace,
        Undo,
        Heading,
        RemoveFormat,
        Bold,
        Italic,
        Underline,
        Strikethrough,
        Code,
        Subscript,
        Superscript,
        Link,
        Table,
        TableToolbar,
        TableProperties,
        TableCellProperties,
        Footnote,
        List,
        ListProperties,
        Image,
        ImageCaption,
        ImageResize,
        ImageStyle,
        ImageToolbar,
        ImageInsert,
        LinkImage,
        SimpleUploadAdapter,
        BlockQuote,
        Alignment,
        Indent,
        IndentBlock,
        SourceEditing,
        Fullscreen,
        Font,
        MediaEmbed,
        SpecialCharacters,
        SpecialCharactersEssentials,
        Emoji,
        Mention,
    ],

    heading: {
        options: [
            {
                model: "paragraph",
                title: "Paragraph",
                class: "ck-heading_paragraph",
            },
            {
                model: "heading1",
                view: "h1",
                title: "Heading 1",
                class: "ck-heading_heading1",
            },
            {
                model: "heading2",
                view: "h2",
                title: "Heading 2",
                class: "ck-heading_heading2",
            },
            {
                model: "heading3",
                view: "h3",
                title: "Heading 3",
                class: "ck-heading_heading3",
            },
        ],
    },

    table: {
        contentToolbar: [
            "tableColumn",
            "tableRow",
            "mergeTableCells",
            "tableProperties",
            "tableCellProperties",
        ],
    },

    list: {
        properties: {
            styles: true,
            startIndex: true,
            reversed: true,
        },
    },

    image: {
        insert: {
            integrations: ["upload", "url"],
        },
        toolbar: [
            "imageStyle:block",
            "imageStyle:side",
            "|",
            "toggleImageCaption",
            "imageTextAlternative",
            "|",
            "linkImage",
        ],
    },

    simpleUpload: {
        // Оскільки це звичайний JS файл, переконайся, що глобальна функція route() від Ziggy доступна в браузері
        uploadUrl:
            typeof route !== "undefined"
                ? route("api.upload.image")
                : "/api/upload-image",
        withCredentials: true,
    },

    emoji: {
        dropdownLimit: 5,
        skinTone: "medium",
    },

    fontSize: {
        options: [
            10,
            12,
            14,
            16,
            { title: "Default", model: "18px" },
            20,
            22,
            24,
            26,
            36,
            48,
        ],
        supportAllValues: true,
    },

    toolbar: [
        "findAndReplace",
        "|",
        "undo",
        "redo",
        "|",
        "removeFormat",
        "heading",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "code",
        "|",
        "subscript",
        "superscript",
        "|",
        "fontSize",
        "fontFamily",
        "fontColor",
        "fontBackgroundColor",
        "|",
        "alignment",
        "outdent",
        "indent",
        "|",
        "insertFootnote",
        "link",
        "insertTable",
        "insertImage",
        "|",
        "emoji",
        "specialCharacters",
        "blockQuote",
        "bulletedList",
        "numberedList",
        "|",
        "sourceEditing",
        "|",
        "fullscreen",
    ],
};
